package com.wuwei.han1meviewer.ui.theme

import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF904A43)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFFFDAD5)
val onPrimaryContainerLight = Color(0xFF73342D)
val secondaryLight = Color(0xFF775652)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFFFDAD5)
val onSecondaryContainerLight = Color(0xFF5D3F3C)
val tertiaryLight = Color(0xFF715B2E)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFFDDFA6)
val onTertiaryContainerLight = Color(0xFF574419)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF93000A)
val backgroundLight = Color(0xFFFFF8F7)
val onBackgroundLight = Color(0xFF231918)
val surfaceLight = Color(0xFFFFF8F7)
val onSurfaceLight = Color(0xFF231918)
val surfaceVariantLight = Color(0xFFF5DDDA)
val onSurfaceVariantLight = Color(0xFF534341)
val outlineLight = Color(0xFF857371)
val outlineVariantLight = Color(0xFFD8C2BF)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF392E2D)
val inverseOnSurfaceLight = Color(0xFFFFEDEA)
val inversePrimaryLight = Color(0xFFFFB4AB)
val surfaceDimLight = Color(0xFFE8D6D4)
val surfaceBrightLight = Color(0xFFFFF8F7)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFFFF0EE)
val surfaceContainerLight = Color(0xFFFCEAE7)
val surfaceContainerHighLight = Color(0xFFF6E4E2)
val surfaceContainerHighestLight = Color(0xFFF1DEDC)

val primaryLightMediumContrast = Color(0xFF5E231E)
val onPrimaryLightMediumContrast = Color(0xFFFFFFFF)
val primaryContainerLightMediumContrast = Color(0xFFA25850)
val onPrimaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val secondaryLightMediumContrast = Color(0xFF4B2F2C)
val onSecondaryLightMediumContrast = Color(0xFFFFFFFF)
val secondaryContainerLightMediumContrast = Color(0xFF876561)
val onSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryLightMediumContrast = Color(0xFF453309)
val onTertiaryLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightMediumContrast = Color(0xFF816A3B)
val onTertiaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val errorLightMediumContrast = Color(0xFF740006)
val onErrorLightMediumContrast = Color(0xFFFFFFFF)
val errorContainerLightMediumContrast = Color(0xFFCF2C27)
val onErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
val backgroundLightMediumContrast = Color(0xFFFFF8F7)
val onBackgroundLightMediumContrast = Color(0xFF231918)
val surfaceLightMediumContrast = Color(0xFFFFF8F7)
val onSurfaceLightMediumContrast = Color(0xFF180F0E)
val surfaceVariantLightMediumContrast = Color(0xFFF5DDDA)
val onSurfaceVariantLightMediumContrast = Color(0xFF413331)
val outlineLightMediumContrast = Color(0xFF5F4F4D)
val outlineVariantLightMediumContrast = Color(0xFF7B6967)
val scrimLightMediumContrast = Color(0xFF000000)
val inverseSurfaceLightMediumContrast = Color(0xFF392E2D)
val inverseOnSurfaceLightMediumContrast = Color(0xFFFFEDEA)
val inversePrimaryLightMediumContrast = Color(0xFFFFB4AB)
val surfaceDimLightMediumContrast = Color(0xFFD4C3C0)
val surfaceBrightLightMediumContrast = Color(0xFFFFF8F7)
val surfaceContainerLowestLightMediumContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightMediumContrast = Color(0xFFFFF0EE)
val surfaceContainerLightMediumContrast = Color(0xFFF6E4E2)
val surfaceContainerHighLightMediumContrast = Color(0xFFEBD9D6)
val surfaceContainerHighestLightMediumContrast = Color(0xFFDFCECB)

val primaryLightHighContrast = Color(0xFF511A15)
val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
val primaryContainerLightHighContrast = Color(0xFF76362F)
val onPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
val secondaryLightHighContrast = Color(0xFF3F2522)
val onSecondaryLightHighContrast = Color(0xFFFFFFFF)
val secondaryContainerLightHighContrast = Color(0xFF60423E)
val onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
val tertiaryLightHighContrast = Color(0xFF3A2902)
val onTertiaryLightHighContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightHighContrast = Color(0xFF5A461B)
val onTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
val errorLightHighContrast = Color(0xFF600004)
val onErrorLightHighContrast = Color(0xFFFFFFFF)
val errorContainerLightHighContrast = Color(0xFF98000A)
val onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
val backgroundLightHighContrast = Color(0xFFFFF8F7)
val onBackgroundLightHighContrast = Color(0xFF231918)
val surfaceLightHighContrast = Color(0xFFFFF8F7)
val onSurfaceLightHighContrast = Color(0xFF000000)
val surfaceVariantLightHighContrast = Color(0xFFF5DDDA)
val onSurfaceVariantLightHighContrast = Color(0xFF000000)
val outlineLightHighContrast = Color(0xFF362927)
val outlineVariantLightHighContrast = Color(0xFF554544)
val scrimLightHighContrast = Color(0xFF000000)
val inverseSurfaceLightHighContrast = Color(0xFF392E2D)
val inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
val inversePrimaryLightHighContrast = Color(0xFFFFB4AB)
val surfaceDimLightHighContrast = Color(0xFFC6B5B3)
val surfaceBrightLightHighContrast = Color(0xFFFFF8F7)
val surfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightHighContrast = Color(0xFFFFEDEA)
val surfaceContainerLightHighContrast = Color(0xFFF1DEDC)
val surfaceContainerHighLightHighContrast = Color(0xFFE2D0CE)
val surfaceContainerHighestLightHighContrast = Color(0xFFD4C3C0)

val primaryDark = Color(0xFFFFB4AB)
val onPrimaryDark = Color(0xFF561E19)
val primaryContainerDark = Color(0xFF73342D)
val onPrimaryContainerDark = Color(0xFFFFDAD5)
val secondaryDark = Color(0xFFE7BDB7)
val onSecondaryDark = Color(0xFF442926)
val secondaryContainerDark = Color(0xFF5D3F3C)
val onSecondaryContainerDark = Color(0xFFFFDAD5)
val tertiaryDark = Color(0xFFE0C38C)
val onTertiaryDark = Color(0xFF3F2E04)
val tertiaryContainerDark = Color(0xFF574419)
val onTertiaryContainerDark = Color(0xFFFDDFA6)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF1A1110)
val onBackgroundDark = Color(0xFFF1DEDC)
val surfaceDark = Color(0xFF1A1110)
val onSurfaceDark = Color(0xFFF1DEDC)
val surfaceVariantDark = Color(0xFF534341)
val onSurfaceVariantDark = Color(0xFFD8C2BF)
val outlineDark = Color(0xFFA08C8A)
val outlineVariantDark = Color(0xFF534341)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFF1DEDC)
val inverseOnSurfaceDark = Color(0xFF392E2D)
val inversePrimaryDark = Color(0xFF904A43)
val surfaceDimDark = Color(0xFF1A1110)
val surfaceBrightDark = Color(0xFF423735)
val surfaceContainerLowestDark = Color(0xFF140C0B)
val surfaceContainerLowDark = Color(0xFF231918)
val surfaceContainerDark = Color(0xFF271D1C)
val surfaceContainerHighDark = Color(0xFF322826)
val surfaceContainerHighestDark = Color(0xFF3D3231)

val primaryDarkMediumContrast = Color(0xFFFFD2CC)
val onPrimaryDarkMediumContrast = Color(0xFF48130F)
val primaryContainerDarkMediumContrast = Color(0xFFCC7B72)
val onPrimaryContainerDarkMediumContrast = Color(0xFF000000)
val secondaryDarkMediumContrast = Color(0xFFFED2CD)
val onSecondaryDarkMediumContrast = Color(0xFF381F1C)
val secondaryContainerDarkMediumContrast = Color(0xFFAD8883)
val onSecondaryContainerDarkMediumContrast = Color(0xFF000000)
val tertiaryDarkMediumContrast = Color(0xFFF7D9A0)
val onTertiaryDarkMediumContrast = Color(0xFF322300)
val tertiaryContainerDarkMediumContrast = Color(0xFFA78D5B)
val onTertiaryContainerDarkMediumContrast = Color(0xFF000000)
val errorDarkMediumContrast = Color(0xFFFFD2CC)
val onErrorDarkMediumContrast = Color(0xFF540003)
val errorContainerDarkMediumContrast = Color(0xFFFF5449)
val onErrorContainerDarkMediumContrast = Color(0xFF000000)
val backgroundDarkMediumContrast = Color(0xFF1A1110)
val onBackgroundDarkMediumContrast = Color(0xFFF1DEDC)
val surfaceDarkMediumContrast = Color(0xFF1A1110)
val onSurfaceDarkMediumContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkMediumContrast = Color(0xFF534341)
val onSurfaceVariantDarkMediumContrast = Color(0xFFEED7D4)
val outlineDarkMediumContrast = Color(0xFFC2ADAA)
val outlineVariantDarkMediumContrast = Color(0xFFA08C89)
val scrimDarkMediumContrast = Color(0xFF000000)
val inverseSurfaceDarkMediumContrast = Color(0xFFF1DEDC)
val inverseOnSurfaceDarkMediumContrast = Color(0xFF322826)
val inversePrimaryDarkMediumContrast = Color(0xFF74352E)
val surfaceDimDarkMediumContrast = Color(0xFF1A1110)
val surfaceBrightDarkMediumContrast = Color(0xFF4D4240)
val surfaceContainerLowestDarkMediumContrast = Color(0xFF0D0605)
val surfaceContainerLowDarkMediumContrast = Color(0xFF251B1A)
val surfaceContainerDarkMediumContrast = Color(0xFF302524)
val surfaceContainerHighDarkMediumContrast = Color(0xFF3B302F)
val surfaceContainerHighestDarkMediumContrast = Color(0xFF463B3A)

val primaryDarkHighContrast = Color(0xFFFFECE9)
val onPrimaryDarkHighContrast = Color(0xFF000000)
val primaryContainerDarkHighContrast = Color(0xFFFFAEA4)
val onPrimaryContainerDarkHighContrast = Color(0xFF220000)
val secondaryDarkHighContrast = Color(0xFFFFECE9)
val onSecondaryDarkHighContrast = Color(0xFF000000)
val secondaryContainerDarkHighContrast = Color(0xFFE3B9B4)
val onSecondaryContainerDarkHighContrast = Color(0xFF190604)
val tertiaryDarkHighContrast = Color(0xFFFFEED2)
val onTertiaryDarkHighContrast = Color(0xFF000000)
val tertiaryContainerDarkHighContrast = Color(0xFFDBBF89)
val onTertiaryContainerDarkHighContrast = Color(0xFF110A00)
val errorDarkHighContrast = Color(0xFFFFECE9)
val onErrorDarkHighContrast = Color(0xFF000000)
val errorContainerDarkHighContrast = Color(0xFFFFAEA4)
val onErrorContainerDarkHighContrast = Color(0xFF220001)
val backgroundDarkHighContrast = Color(0xFF1A1110)
val onBackgroundDarkHighContrast = Color(0xFFF1DEDC)
val surfaceDarkHighContrast = Color(0xFF1A1110)
val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkHighContrast = Color(0xFF534341)
val onSurfaceVariantDarkHighContrast = Color(0xFFFFFFFF)
val outlineDarkHighContrast = Color(0xFFFFECE9)
val outlineVariantDarkHighContrast = Color(0xFFD4BEBB)
val scrimDarkHighContrast = Color(0xFF000000)
val inverseSurfaceDarkHighContrast = Color(0xFFF1DEDC)
val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
val inversePrimaryDarkHighContrast = Color(0xFF74352E)
val surfaceDimDarkHighContrast = Color(0xFF1A1110)
val surfaceBrightDarkHighContrast = Color(0xFF5A4D4C)
val surfaceContainerLowestDarkHighContrast = Color(0xFF000000)
val surfaceContainerLowDarkHighContrast = Color(0xFF271D1C)
val surfaceContainerDarkHighContrast = Color(0xFF392E2D)
val surfaceContainerHighDarkHighContrast = Color(0xFF443937)
val surfaceContainerHighestDarkHighContrast = Color(0xFF504443)















